#ifndef XLIB_PREPROCESSOR_FACILITIES_CAT_HPP_
#define XLIB_PREPROCESSOR_FACILITIES_CAT_HPP_

#define XLIB_PP_CAT(X, ...) _XLIB_PP_CAT(X, __VA_ARGS__)
#define _XLIB_PP_CAT(X, ...) X##__VA_ARGS__

#endif  // XLIB_PREPROCESSOR_FACILITIES_CAT_HPP_
