#ifndef XLIB_PREPROCESSOR_FACILITIES_PROBE_HPP_
#define XLIB_PREPROCESSOR_FACILITIES_PROBE_HPP_

#define XLIB_PP_PROBE(X) X, 1,
#define XLIB_PP_PROBE_N(X, N) X, N,

#endif  // XLIB_PREPROCESSOR_FACILITIES_PROBE_HPP_
